### ISSUE TITLE
the data is lost when the another row or column is deleted

### ISSUE THREAD

**Issue by MrH2H** [Spreadsheets/WickedGrid#108]
if the attribute is added to the TD, and the data is lost when the another row or column is deleted.

like this:
1.insert the data and attribute
![rowdata](https://cloud.githubusercontent.com/assets/19909689/21919737/af065834-d997-11e6-9a49-922d0ae0f74a.png)
2.delete the  row. 
![delete](https://cloud.githubusercontent.com/assets/19909689/21919740/bc45f48c-d997-11e6-8ffe-f654a49e6eab.png)
the data of row 1  is lost.

I don't know if this is a bug.

**Comment by robertleeplummerjr** [comment]
Care to share findings?
